# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/

name = "chatkitauth"
main = ".open-next/worker.js"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[observability]
enabled = true

[placement]
mode = "smart"

[[d1_databases]]
binding = "LOGINBINDS"
database_name = "logindb"
database_id = "6e522b4b-4d98-4851-bd4b-a69102ebede5"
migrations_dir = "drizzle"


# To protect the database id, we ignore this
# file when committing to the repo by running once:
# git update-index --assume-unchanged wrangler.toml
#
# Put back in git if you need to commit this file:
# git update-index --no-assume-unchanged wrangler.toml